spring.application.name=activityservice

server.port=9091

#mongodb://localhost:27017

spring.data.mongodb.uri=mongodb://localhost:27017/activites_db

spring.data.mongodb.database=activites_db

eureka.client.service-url.defaulZone=http://localhost:8761/eureka/

